k9s:
  cluster: cc01
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - auxiliary
      - dev
      - prod
      - all
      - default
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
