k9s:
  cluster: boundary-complero
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - auxiliary
      - mogenius
      - prod
      - velero
      - dev
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
